//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal res() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ekassa.Resources.res", typeof(res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Kassa nəzarət mexanizmi qurğusu ilə təchiz edilmiş yeni növ proqram-aparat kompleksidir. E-kassa vasitəsi ilə alınmış və emal edilmiş çek məlumatlarının, habelə həyata keçirilən əməliyyatlar barədə məlumatlarının yığılması, emalı, saxlanılması və real vaxt rejimində Dövlət Vergi Xidmətinin informasiya sistemləri bazasına ötürülməsi (köçürülməsi) təmin edilir. E-kassa pərakəndə ticarət və (və ya) ictimai iaşə fəaliyyəti üzrə əhali ilə pul hesablaşmalarının aparmasında istifadə edilir..
        /// </summary>
        public static string a1 {
            get {
                return ResourceManager.GetString("a1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aşağıdakı fəaliyyət növləri istisna olmaqla, pərakəndə ticarət və (və ya) ictimai iaşə fəaliyyəti üzrə nağd pul hesablaşmaları müəyyən edilmiş meyarlara cavab verən və Dövlət Vergi Xidmətinin elektron informasiya sisteminə qoşulan e-kassa vasitəsilə həyata keçirilməlidir.
        ///      • Qəzet və jurnalların satışı (belə satış dövriyyəsinin ümumi dövriyyədəki payı 50 faizdən çox olduqda);
        ///      • Kənd təsərrüfatı məhsullarının bazarlarda, yarmarkalarda və səyyar qaydada satışı;
        ///    • Səyyar, bazarlarda və digər  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string a2 {
            get {
                return ResourceManager.GetString("a2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asan və surətli satış prosesi. Satış prosesin ən kritik məsələlərindən biri kassada müştərini ləngitməməkdir. Bu prosesi sürətləndirmək üçün &quot;ERP-SOFT Online Kassa&quot; həlli köməyinizdə olacaq. 1C proqramda satış keçirməklə e-kassa aparatına məlumat avtomatik ötürüləcəkdir..
        /// </summary>
        public static string a3 {
            get {
                return ResourceManager.GetString("a3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hal hazırda inteqrasiya olunub Az Smart Mobile e-kassa aparatı ilə..
        /// </summary>
        public static string a4 {
            get {
                return ResourceManager.GetString("a4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to «ERP-SOFT: E-KASSA» həlli 1C 8.x platformasında yazılmış proqramlar üçün yaradılıb. Eyni zamanda 1C: Ticarətin idarəedilməsi 10.3, 1C: Upravleniye proizvodstvennım predpriyatiyem və 1C: Kompleksnaya avtomatizaciya üçün yararlıdır..
        /// </summary>
        public static string a5 {
            get {
                return ResourceManager.GetString("a5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bəli, mümkündür. «ERP-SOFT: E-KASSA» həllində həmin funksional mövcutdur..
        /// </summary>
        public static string a6 {
            get {
                return ResourceManager.GetString("a6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-kassanı 1C proqrama qoşulması üç iş günü ərzində həyata keçirilir. Qeyd edək ki proqramda dəyişikliklər olunmayıbsa iki iş gün ərzində qoşmaq mümkündür..
        /// </summary>
        public static string a7 {
            get {
                return ResourceManager.GetString("a7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERP-SOFT MMC rəsmi 1C françayzidir və 1C proqramı Sizin üçün reşəkar mütəxəssizlərimiz tərəfdən quraşdırıla bilər..
        /// </summary>
        public static string a8 {
            get {
                return ResourceManager.GetString("a8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ünvan: Azərbaycan, Bakı ş., Azadlıq pr. 74.
        /// </summary>
        public static string address {
            get {
                return ResourceManager.GetString("address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bizə zəng edin:.
        /// </summary>
        public static string CallUs {
            get {
                return ResourceManager.GetString("CallUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Kassanız yoxdursa əldə edin.
        /// </summary>
        public static string con1 {
            get {
                return ResourceManager.GetString("con1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERP-SOFT-a zəng edin və mütəxəssisimizin çağrışına sifariş edin. Sizinlə müqavilə bağlanacaq.
        /// </summary>
        public static string con2 {
            get {
                return ResourceManager.GetString("con2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERP-SOFT mütəxəssisləri 1C-də lazımı dayişikliklər edəcək və E-Kassanıza qoşulma işində kömək edəcəklər.
        /// </summary>
        public static string con3 {
            get {
                return ResourceManager.GetString("con3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hesabınızdaki balansınızı artırın və 1C-dən E-Kassailə işləmək rahatlığından zövq alın..
        /// </summary>
        public static string con4 {
            get {
                return ResourceManager.GetString("con4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-KASSANI qoşmaq.
        /// </summary>
        public static string connect {
            get {
                return ResourceManager.GetString("connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-KASSAnı 1C proqrama necə qoşum.
        /// </summary>
        public static string howToConnect {
            get {
                return ResourceManager.GetString("howToConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dil.
        /// </summary>
        public static string lang {
            get {
                return ResourceManager.GetString("lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-KASSA ayda 5 manata.
        /// </summary>
        public static string MainHeader {
            get {
                return ResourceManager.GetString("MainHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon:.
        /// </summary>
        public static string phone {
            get {
                return ResourceManager.GetString("phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ayda cəmi 5 manata.
        /// </summary>
        public static string price {
            get {
                return ResourceManager.GetString("price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Kassa nədir?.
        /// </summary>
        public static string q1 {
            get {
                return ResourceManager.GetString("q1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-kassa kimə lazımdır?.
        /// </summary>
        public static string q2 {
            get {
                return ResourceManager.GetString("q2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nə üçün e-kassanı 1C proqrama qoşmaq lazımdır?.
        /// </summary>
        public static string q3 {
            get {
                return ResourceManager.GetString("q3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hansı kassa aparatı 1C proqrama qoşmaq olar?.
        /// </summary>
        public static string q4 {
            get {
                return ResourceManager.GetString("q4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hansı 1C proqramı e-kassaya qoşmaq olar?.
        /// </summary>
        public static string q5 {
            get {
                return ResourceManager.GetString("q5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proqram RDP serverdə olduqda e-kassaya qoşmaq mümkündür?.
        /// </summary>
        public static string q6 {
            get {
                return ResourceManager.GetString("q6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hansı müddət ərzində qoşursuz?.
        /// </summary>
        public static string q7 {
            get {
                return ResourceManager.GetString("q7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proqram yoxdursa nə etmək olar?.
        /// </summary>
        public static string q8 {
            get {
                return ResourceManager.GetString("q8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suallar və cavablar.
        /// </summary>
        public static string questAnswer {
            get {
                return ResourceManager.GetString("questAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sual ver.
        /// </summary>
        public static string question {
            get {
                return ResourceManager.GetString("question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menecerlərimizə sual verin və sifariş edin.
        /// </summary>
        public static string questionToManager {
            get {
                return ResourceManager.GetString("questionToManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qoşulmaq hazırsınız?.
        /// </summary>
        public static string ready {
            get {
                return ResourceManager.GetString("ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sizin 1Cilə e-kassanın əlagəndirilməsi üçün həll var. &quot;ERP-SOFT: E-KASSA&quot;.
        /// </summary>
        public static string subTitle {
            get {
                return ResourceManager.GetString("subTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sərfəli qiymət.
        /// </summary>
        public static string t1 {
            get {
                return ResourceManager.GetString("t1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asan qoşulma.
        /// </summary>
        public static string t2 {
            get {
                return ResourceManager.GetString("t2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tam uyğunluq.
        /// </summary>
        public static string t3 {
            get {
                return ResourceManager.GetString("t3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rahat istifadə.
        /// </summary>
        public static string t4 {
            get {
                return ResourceManager.GetString("t4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERP-SOFT: OnlineKassa.
        /// </summary>
        public static string Tille {
            get {
                return ResourceManager.GetString("Tille", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sərfəli qiymət və yeniliklər. E-kassa sayınız artdıqca qiymət daha sərfəli olacaq..
        /// </summary>
        public static string txt1 {
            get {
                return ResourceManager.GetString("txt1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-kassanı 1C proqrama qoşulması üç iş günü ərzində həyata keçirilir. Qeyd edək ki proqramda dəyişikliklər olunmayıbsa iki iş gün ərzində qoşmaq mümkündür.
        /// </summary>
        public static string txt2 {
            get {
                return ResourceManager.GetString("txt2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1356-VQD saylı qanuna tam uyğunluq. 1 iyul 2019-ci il tarixindən etibarən ticarət obyektlərin kassaları yenilənəcək və yeni qəbz nümunələri veriləcək..
        /// </summary>
        public static string txt3 {
            get {
                return ResourceManager.GetString("txt3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texniki məsələlər üzrə 24/7, xidmətinizdəyik. Bütün suallara cavab ala bilərsiz..
        /// </summary>
        public static string txt4 {
            get {
                return ResourceManager.GetString("txt4", resourceCulture);
            }
        }
    }
}
